splash-screen: true

features:
  holograms: true
  boards: true
  tablist: true
  emoji: true
  animations: true
  chat-bubbles: true
  damage-indicators: true
  drops: true

hotload:
  watch-interval-ticks: 20

holograms:
  stack-distance: 0.26
  update-interval-ticks: 10
  view-range: 48.0
  per-viewer-placeholders: true
  temporary-update-interval-ticks: 2
  text-art-max-width: 48

boards:
  update-interval-ticks: 20

tablist:
  use-header-footers: true
  header: "&d&lGloss"
  footer: "&7VolmitSoftware.com"
  update-interval-ticks: 40
  group-list-names: true

groups:
  use-vault: true

emoji:
  emoji-specific-permissions: false
  tab-complete: true

text:
  placeholders: true
  functions: true

chat:
  color: true

chat-bubbles:
  follow-players: true
  hide-own-messages: true
  word-wrap-break-chars: 32
  max-time-alive: 5000
  line-stagger-ticks: 5
  fly-away: true
  message:
    prefix: "&7"
    offset:
      x: 0.0
      y: 1.0
      z: 0.0
  blacklist-worlds: []

damage-indicators:
  motion:
    random-throw-force: 0.08
    initial-up-force: 0.13
    gravity-factor: 0.0093
  max-indicators-per-second: 40
  max-ms-alive: 3000
  damage-indicator-prefix: "&c&l"
  heal-indicator-prefix: "&a&l"
  decimals: 0
  show-heals: true

drops:
  name-format: "&7{count}x {type}"

motd:
  enabled: false
  texts:
    - "&dA glossy server"

commands:
  sounds: true

metrics: true
